package akasha.gl;

import java.lang.annotation.Documented;
import javax.annotation.Generated;
import javax.annotation.Nonnull;
import org.intellij.lang.annotations.MagicConstant;

@Generated("org.realityforge.webtack")
@Documented
@MagicConstant(
    intValues = {
        WebGL2RenderingContext.LINE_WIDTH,
        WebGL2RenderingContext.CULL_FACE,
        WebGL2RenderingContext.CULL_FACE_MODE,
        WebGL2RenderingContext.FRONT_FACE,
        WebGL2RenderingContext.DEPTH_RANGE,
        WebGL2RenderingContext.DEPTH_TEST,
        WebGL2RenderingContext.DEPTH_WRITEMASK,
        WebGL2RenderingContext.DEPTH_CLEAR_VALUE,
        WebGL2RenderingContext.DEPTH_FUNC,
        WebGL2RenderingContext.STENCIL_TEST,
        WebGL2RenderingContext.STENCIL_CLEAR_VALUE,
        WebGL2RenderingContext.STENCIL_FUNC,
        WebGL2RenderingContext.STENCIL_VALUE_MASK,
        WebGL2RenderingContext.STENCIL_FAIL,
        WebGL2RenderingContext.STENCIL_PASS_DEPTH_FAIL,
        WebGL2RenderingContext.STENCIL_PASS_DEPTH_PASS,
        WebGL2RenderingContext.STENCIL_REF,
        WebGL2RenderingContext.STENCIL_WRITEMASK,
        WebGL2RenderingContext.VIEWPORT,
        WebGL2RenderingContext.DITHER,
        WebGL2RenderingContext.BLEND,
        WebGL2RenderingContext.READ_BUFFER,
        WebGL2RenderingContext.SCISSOR_BOX,
        WebGL2RenderingContext.SCISSOR_TEST,
        WebGL2RenderingContext.COLOR_CLEAR_VALUE,
        WebGL2RenderingContext.COLOR_WRITEMASK,
        WebGL2RenderingContext.UNPACK_ROW_LENGTH,
        WebGL2RenderingContext.UNPACK_SKIP_ROWS,
        WebGL2RenderingContext.UNPACK_SKIP_PIXELS,
        WebGL2RenderingContext.UNPACK_ALIGNMENT,
        WebGL2RenderingContext.PACK_ROW_LENGTH,
        WebGL2RenderingContext.PACK_SKIP_ROWS,
        WebGL2RenderingContext.PACK_SKIP_PIXELS,
        WebGL2RenderingContext.PACK_ALIGNMENT,
        WebGL2RenderingContext.MAX_TEXTURE_SIZE,
        WebGL2RenderingContext.MAX_VIEWPORT_DIMS,
        WebGL2RenderingContext.SUBPIXEL_BITS,
        WebGL2RenderingContext.RED_BITS,
        WebGL2RenderingContext.GREEN_BITS,
        WebGL2RenderingContext.BLUE_BITS,
        WebGL2RenderingContext.ALPHA_BITS,
        WebGL2RenderingContext.DEPTH_BITS,
        WebGL2RenderingContext.STENCIL_BITS,
        WebGL2RenderingContext.VENDOR,
        WebGL2RenderingContext.RENDERER,
        WebGL2RenderingContext.VERSION,
        WebGL2RenderingContext.POLYGON_OFFSET_UNITS,
        WebGL2RenderingContext.BLEND_COLOR,
        WebGL2RenderingContext.BLEND_EQUATION,
        WebGL2RenderingContext.BLEND_EQUATION_RGB,
        WebGL2RenderingContext.POLYGON_OFFSET_FILL,
        WebGL2RenderingContext.POLYGON_OFFSET_FACTOR,
        WebGL2RenderingContext.TEXTURE_BINDING_2D,
        WebGL2RenderingContext.TEXTURE_BINDING_3D,
        WebGL2RenderingContext.UNPACK_SKIP_IMAGES,
        WebGL2RenderingContext.UNPACK_IMAGE_HEIGHT,
        WebGL2RenderingContext.MAX_3D_TEXTURE_SIZE,
        WebGL2RenderingContext.SAMPLE_ALPHA_TO_COVERAGE,
        WebGL2RenderingContext.SAMPLE_COVERAGE,
        WebGL2RenderingContext.SAMPLE_BUFFERS,
        WebGL2RenderingContext.SAMPLES,
        WebGL2RenderingContext.SAMPLE_COVERAGE_VALUE,
        WebGL2RenderingContext.SAMPLE_COVERAGE_INVERT,
        WebGL2RenderingContext.BLEND_DST_RGB,
        WebGL2RenderingContext.BLEND_SRC_RGB,
        WebGL2RenderingContext.BLEND_DST_ALPHA,
        WebGL2RenderingContext.BLEND_SRC_ALPHA,
        WebGL2RenderingContext.MAX_ELEMENTS_VERTICES,
        WebGL2RenderingContext.MAX_ELEMENTS_INDICES,
        WebGL2RenderingContext.GENERATE_MIPMAP_HINT,
        WebGL2RenderingContext.ALIASED_POINT_SIZE_RANGE,
        WebGL2RenderingContext.ALIASED_LINE_WIDTH_RANGE,
        WebGL2RenderingContext.ACTIVE_TEXTURE,
        WebGL2RenderingContext.MAX_RENDERBUFFER_SIZE,
        WebGL2RenderingContext.MAX_TEXTURE_LOD_BIAS,
        EXT_texture_filter_anisotropic.MAX_TEXTURE_MAX_ANISOTROPY_EXT,
        WebGL2RenderingContext.TEXTURE_BINDING_CUBE_MAP,
        WebGL2RenderingContext.MAX_CUBE_MAP_TEXTURE_SIZE,
        WebGL2RenderingContext.VERTEX_ARRAY_BINDING,
        WebGL2RenderingContext.COMPRESSED_TEXTURE_FORMATS,
        WebGL2RenderingContext.STENCIL_BACK_FUNC,
        WebGL2RenderingContext.STENCIL_BACK_FAIL,
        WebGL2RenderingContext.STENCIL_BACK_PASS_DEPTH_FAIL,
        WebGL2RenderingContext.STENCIL_BACK_PASS_DEPTH_PASS,
        WebGL2RenderingContext.MAX_DRAW_BUFFERS,
        WebGL2RenderingContext.DRAW_BUFFER0,
        WebGL2RenderingContext.DRAW_BUFFER1,
        WebGL2RenderingContext.DRAW_BUFFER2,
        WebGL2RenderingContext.DRAW_BUFFER3,
        WebGL2RenderingContext.DRAW_BUFFER4,
        WebGL2RenderingContext.DRAW_BUFFER5,
        WebGL2RenderingContext.DRAW_BUFFER6,
        WebGL2RenderingContext.DRAW_BUFFER7,
        WebGL2RenderingContext.DRAW_BUFFER8,
        WebGL2RenderingContext.DRAW_BUFFER9,
        WebGL2RenderingContext.DRAW_BUFFER10,
        WebGL2RenderingContext.DRAW_BUFFER11,
        WebGL2RenderingContext.DRAW_BUFFER12,
        WebGL2RenderingContext.DRAW_BUFFER13,
        WebGL2RenderingContext.DRAW_BUFFER14,
        WebGL2RenderingContext.DRAW_BUFFER15,
        WebGL2RenderingContext.BLEND_EQUATION_ALPHA,
        WebGL2RenderingContext.MAX_VERTEX_ATTRIBS,
        WebGL2RenderingContext.MAX_TEXTURE_IMAGE_UNITS,
        WebGL2RenderingContext.ARRAY_BUFFER_BINDING,
        WebGL2RenderingContext.ELEMENT_ARRAY_BUFFER_BINDING,
        WebGL2RenderingContext.PIXEL_PACK_BUFFER_BINDING,
        WebGL2RenderingContext.PIXEL_UNPACK_BUFFER_BINDING,
        WebGL2RenderingContext.MAX_ARRAY_TEXTURE_LAYERS,
        WebGL2RenderingContext.MIN_PROGRAM_TEXEL_OFFSET,
        WebGL2RenderingContext.MAX_PROGRAM_TEXEL_OFFSET,
        WebGL2RenderingContext.SAMPLER_BINDING,
        WebGL2RenderingContext.UNIFORM_BUFFER_BINDING,
        WebGL2RenderingContext.MAX_VERTEX_UNIFORM_BLOCKS,
        WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_BLOCKS,
        WebGL2RenderingContext.MAX_COMBINED_UNIFORM_BLOCKS,
        WebGL2RenderingContext.MAX_UNIFORM_BUFFER_BINDINGS,
        WebGL2RenderingContext.MAX_UNIFORM_BLOCK_SIZE,
        WebGL2RenderingContext.MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS,
        WebGL2RenderingContext.MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS,
        WebGL2RenderingContext.UNIFORM_BUFFER_OFFSET_ALIGNMENT,
        WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_COMPONENTS,
        WebGL2RenderingContext.MAX_VERTEX_UNIFORM_COMPONENTS,
        WebGL2RenderingContext.MAX_VARYING_COMPONENTS,
        WebGL2RenderingContext.MAX_VERTEX_TEXTURE_IMAGE_UNITS,
        WebGL2RenderingContext.MAX_COMBINED_TEXTURE_IMAGE_UNITS,
        WebGL2RenderingContext.FRAGMENT_SHADER_DERIVATIVE_HINT,
        WebGL2RenderingContext.SHADING_LANGUAGE_VERSION,
        WebGL2RenderingContext.CURRENT_PROGRAM,
        WebGL2RenderingContext.IMPLEMENTATION_COLOR_READ_TYPE,
        WebGL2RenderingContext.IMPLEMENTATION_COLOR_READ_FORMAT,
        WebGL2RenderingContext.TEXTURE_BINDING_2D_ARRAY,
        WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS,
        WebGL2RenderingContext.RASTERIZER_DISCARD,
        WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS,
        WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS,
        WebGL2RenderingContext.TRANSFORM_FEEDBACK_BUFFER_BINDING,
        WebGL2RenderingContext.STENCIL_BACK_REF,
        WebGL2RenderingContext.STENCIL_BACK_VALUE_MASK,
        WebGL2RenderingContext.STENCIL_BACK_WRITEMASK,
        WebGL2RenderingContext.DRAW_FRAMEBUFFER_BINDING,
        WebGL2RenderingContext.FRAMEBUFFER_BINDING,
        WebGL2RenderingContext.RENDERBUFFER_BINDING,
        WebGL2RenderingContext.READ_FRAMEBUFFER_BINDING,
        WebGL2RenderingContext.MAX_COLOR_ATTACHMENTS,
        WebGL2RenderingContext.MAX_SAMPLES,
        WebGL2RenderingContext.MAX_ELEMENT_INDEX,
        WebGL2RenderingContext.MAX_VERTEX_UNIFORM_VECTORS,
        WebGL2RenderingContext.MAX_VARYING_VECTORS,
        WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_VECTORS,
        WebGL2RenderingContext.TRANSFORM_FEEDBACK_PAUSED,
        WebGL2RenderingContext.TRANSFORM_FEEDBACK_ACTIVE,
        WebGL2RenderingContext.TRANSFORM_FEEDBACK_BINDING,
        EXT_disjoint_timer_query_webgl2.TIMESTAMP_EXT,
        WebGL2RenderingContext.COPY_READ_BUFFER_BINDING,
        WebGL2RenderingContext.COPY_WRITE_BUFFER_BINDING,
        EXT_disjoint_timer_query_webgl2.GPU_DISJOINT_EXT,
        WebGL2RenderingContext.MAX_SERVER_WAIT_TIMEOUT,
        WebGL2RenderingContext.MAX_VERTEX_OUTPUT_COMPONENTS,
        WebGL2RenderingContext.MAX_FRAGMENT_INPUT_COMPONENTS,
        WebGL2RenderingContext.UNPACK_FLIP_Y_WEBGL,
        WebGL2RenderingContext.UNPACK_PREMULTIPLY_ALPHA_WEBGL,
        WebGL2RenderingContext.UNPACK_COLORSPACE_CONVERSION_WEBGL,
        WEBGL_debug_renderer_info.UNMASKED_VENDOR_WEBGL,
        WEBGL_debug_renderer_info.UNMASKED_RENDERER_WEBGL,
        WebGL2RenderingContext.MAX_CLIENT_WAIT_TIMEOUT_WEBGL,
        OCULUS_multiview.MAX_VIEWS_OVR,
        OVR_multiview2.MAX_VIEWS_OVR
    }
)
public @interface WebGLParameterName {
  final class Util {
    private Util() {
    }

    @WebGLParameterName
    public static int requireValid(final int value) {
      assertValid( value );
      return value;
    }

    public static void assertValid(final int value) {
      assert isValid( value ) : "@WebGLParameterName annotated value must be one of [WebGL2RenderingContext.ACTIVE_TEXTURE, WebGL2RenderingContext.ALIASED_LINE_WIDTH_RANGE, WebGL2RenderingContext.ALIASED_POINT_SIZE_RANGE, WebGL2RenderingContext.ALPHA_BITS, WebGL2RenderingContext.ARRAY_BUFFER_BINDING, WebGL2RenderingContext.BLEND, WebGL2RenderingContext.BLEND_COLOR, WebGL2RenderingContext.BLEND_DST_ALPHA, WebGL2RenderingContext.BLEND_DST_RGB, WebGL2RenderingContext.BLEND_EQUATION, WebGL2RenderingContext.BLEND_EQUATION_ALPHA, WebGL2RenderingContext.BLEND_EQUATION_RGB, WebGL2RenderingContext.BLEND_SRC_ALPHA, WebGL2RenderingContext.BLEND_SRC_RGB, WebGL2RenderingContext.BLUE_BITS, WebGL2RenderingContext.COLOR_CLEAR_VALUE, WebGL2RenderingContext.COLOR_WRITEMASK, WebGL2RenderingContext.COMPRESSED_TEXTURE_FORMATS, WebGL2RenderingContext.CULL_FACE, WebGL2RenderingContext.CULL_FACE_MODE, WebGL2RenderingContext.CURRENT_PROGRAM, WebGL2RenderingContext.DEPTH_BITS, WebGL2RenderingContext.DEPTH_CLEAR_VALUE, WebGL2RenderingContext.DEPTH_FUNC, WebGL2RenderingContext.DEPTH_RANGE, WebGL2RenderingContext.DEPTH_TEST, WebGL2RenderingContext.DEPTH_WRITEMASK, WebGL2RenderingContext.DITHER, WebGL2RenderingContext.ELEMENT_ARRAY_BUFFER_BINDING, WebGL2RenderingContext.FRAMEBUFFER_BINDING, WebGL2RenderingContext.FRONT_FACE, WebGL2RenderingContext.GENERATE_MIPMAP_HINT, WebGL2RenderingContext.GREEN_BITS, WebGL2RenderingContext.IMPLEMENTATION_COLOR_READ_FORMAT, WebGL2RenderingContext.IMPLEMENTATION_COLOR_READ_TYPE, WebGL2RenderingContext.LINE_WIDTH, WebGL2RenderingContext.MAX_COMBINED_TEXTURE_IMAGE_UNITS, WebGL2RenderingContext.MAX_CUBE_MAP_TEXTURE_SIZE, WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_VECTORS, WebGL2RenderingContext.MAX_RENDERBUFFER_SIZE, WebGL2RenderingContext.MAX_TEXTURE_IMAGE_UNITS, WebGL2RenderingContext.MAX_TEXTURE_SIZE, WebGL2RenderingContext.MAX_VARYING_VECTORS, WebGL2RenderingContext.MAX_VERTEX_ATTRIBS, WebGL2RenderingContext.MAX_VERTEX_TEXTURE_IMAGE_UNITS, WebGL2RenderingContext.MAX_VERTEX_UNIFORM_VECTORS, WebGL2RenderingContext.MAX_VIEWPORT_DIMS, WebGL2RenderingContext.PACK_ALIGNMENT, WebGL2RenderingContext.POLYGON_OFFSET_FACTOR, WebGL2RenderingContext.POLYGON_OFFSET_FILL, WebGL2RenderingContext.POLYGON_OFFSET_UNITS, WebGL2RenderingContext.RED_BITS, WebGL2RenderingContext.RENDERBUFFER_BINDING, WebGL2RenderingContext.RENDERER, WebGL2RenderingContext.SAMPLE_BUFFERS, WebGL2RenderingContext.SAMPLE_COVERAGE_INVERT, WebGL2RenderingContext.SAMPLE_COVERAGE_VALUE, WebGL2RenderingContext.SAMPLES, WebGL2RenderingContext.SCISSOR_BOX, WebGL2RenderingContext.SCISSOR_TEST, WebGL2RenderingContext.SHADING_LANGUAGE_VERSION, WebGL2RenderingContext.STENCIL_BACK_FAIL, WebGL2RenderingContext.STENCIL_BACK_FUNC, WebGL2RenderingContext.STENCIL_BACK_PASS_DEPTH_FAIL, WebGL2RenderingContext.STENCIL_BACK_PASS_DEPTH_PASS, WebGL2RenderingContext.STENCIL_BACK_REF, WebGL2RenderingContext.STENCIL_BACK_VALUE_MASK, WebGL2RenderingContext.STENCIL_BACK_WRITEMASK, WebGL2RenderingContext.STENCIL_BITS, WebGL2RenderingContext.STENCIL_CLEAR_VALUE, WebGL2RenderingContext.STENCIL_FAIL, WebGL2RenderingContext.STENCIL_FUNC, WebGL2RenderingContext.STENCIL_PASS_DEPTH_FAIL, WebGL2RenderingContext.STENCIL_PASS_DEPTH_PASS, WebGL2RenderingContext.STENCIL_REF, WebGL2RenderingContext.STENCIL_TEST, WebGL2RenderingContext.STENCIL_VALUE_MASK, WebGL2RenderingContext.STENCIL_WRITEMASK, WebGL2RenderingContext.SUBPIXEL_BITS, WebGL2RenderingContext.TEXTURE_BINDING_2D, WebGL2RenderingContext.TEXTURE_BINDING_CUBE_MAP, WebGL2RenderingContext.UNPACK_ALIGNMENT, WebGL2RenderingContext.UNPACK_COLORSPACE_CONVERSION_WEBGL, WebGL2RenderingContext.UNPACK_FLIP_Y_WEBGL, WebGL2RenderingContext.UNPACK_PREMULTIPLY_ALPHA_WEBGL, WebGL2RenderingContext.VENDOR, WebGL2RenderingContext.VERSION, WebGL2RenderingContext.VIEWPORT, WebGL2RenderingContext.COPY_READ_BUFFER_BINDING, WebGL2RenderingContext.COPY_WRITE_BUFFER_BINDING, WebGL2RenderingContext.DRAW_BUFFER0, WebGL2RenderingContext.DRAW_BUFFER1, WebGL2RenderingContext.DRAW_BUFFER2, WebGL2RenderingContext.DRAW_BUFFER3, WebGL2RenderingContext.DRAW_BUFFER4, WebGL2RenderingContext.DRAW_BUFFER5, WebGL2RenderingContext.DRAW_BUFFER6, WebGL2RenderingContext.DRAW_BUFFER7, WebGL2RenderingContext.DRAW_BUFFER8, WebGL2RenderingContext.DRAW_BUFFER9, WebGL2RenderingContext.DRAW_BUFFER10, WebGL2RenderingContext.DRAW_BUFFER11, WebGL2RenderingContext.DRAW_BUFFER12, WebGL2RenderingContext.DRAW_BUFFER13, WebGL2RenderingContext.DRAW_BUFFER14, WebGL2RenderingContext.DRAW_BUFFER15, WebGL2RenderingContext.DRAW_FRAMEBUFFER_BINDING, WebGL2RenderingContext.FRAGMENT_SHADER_DERIVATIVE_HINT, WebGL2RenderingContext.MAX_3D_TEXTURE_SIZE, WebGL2RenderingContext.MAX_ARRAY_TEXTURE_LAYERS, WebGL2RenderingContext.MAX_CLIENT_WAIT_TIMEOUT_WEBGL, WebGL2RenderingContext.MAX_COLOR_ATTACHMENTS, WebGL2RenderingContext.MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS, WebGL2RenderingContext.MAX_COMBINED_UNIFORM_BLOCKS, WebGL2RenderingContext.MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS, WebGL2RenderingContext.MAX_DRAW_BUFFERS, WebGL2RenderingContext.MAX_ELEMENT_INDEX, WebGL2RenderingContext.MAX_ELEMENTS_INDICES, WebGL2RenderingContext.MAX_ELEMENTS_VERTICES, WebGL2RenderingContext.MAX_FRAGMENT_INPUT_COMPONENTS, WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_BLOCKS, WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_COMPONENTS, WebGL2RenderingContext.MAX_PROGRAM_TEXEL_OFFSET, WebGL2RenderingContext.MAX_SAMPLES, WebGL2RenderingContext.MAX_SERVER_WAIT_TIMEOUT, WebGL2RenderingContext.MAX_TEXTURE_LOD_BIAS, WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS, WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS, WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS, WebGL2RenderingContext.MAX_UNIFORM_BLOCK_SIZE, WebGL2RenderingContext.MAX_UNIFORM_BUFFER_BINDINGS, WebGL2RenderingContext.MAX_VARYING_COMPONENTS, WebGL2RenderingContext.MAX_VERTEX_OUTPUT_COMPONENTS, WebGL2RenderingContext.MAX_VERTEX_UNIFORM_BLOCKS, WebGL2RenderingContext.MAX_VERTEX_UNIFORM_COMPONENTS, WebGL2RenderingContext.MIN_PROGRAM_TEXEL_OFFSET, WebGL2RenderingContext.PACK_ROW_LENGTH, WebGL2RenderingContext.PACK_SKIP_PIXELS, WebGL2RenderingContext.PACK_SKIP_ROWS, WebGL2RenderingContext.PIXEL_PACK_BUFFER_BINDING, WebGL2RenderingContext.PIXEL_UNPACK_BUFFER_BINDING, WebGL2RenderingContext.RASTERIZER_DISCARD, WebGL2RenderingContext.READ_BUFFER, WebGL2RenderingContext.READ_FRAMEBUFFER_BINDING, WebGL2RenderingContext.SAMPLE_ALPHA_TO_COVERAGE, WebGL2RenderingContext.SAMPLE_COVERAGE, WebGL2RenderingContext.SAMPLER_BINDING, WebGL2RenderingContext.TEXTURE_BINDING_2D_ARRAY, WebGL2RenderingContext.TEXTURE_BINDING_3D, WebGL2RenderingContext.TRANSFORM_FEEDBACK_ACTIVE, WebGL2RenderingContext.TRANSFORM_FEEDBACK_BINDING, WebGL2RenderingContext.TRANSFORM_FEEDBACK_BUFFER_BINDING, WebGL2RenderingContext.TRANSFORM_FEEDBACK_PAUSED, WebGL2RenderingContext.UNIFORM_BUFFER_BINDING, WebGL2RenderingContext.UNIFORM_BUFFER_OFFSET_ALIGNMENT, WebGL2RenderingContext.UNPACK_IMAGE_HEIGHT, WebGL2RenderingContext.UNPACK_ROW_LENGTH, WebGL2RenderingContext.UNPACK_SKIP_IMAGES, WebGL2RenderingContext.UNPACK_SKIP_PIXELS, WebGL2RenderingContext.UNPACK_SKIP_ROWS, WebGL2RenderingContext.VERTEX_ARRAY_BINDING, EXT_disjoint_timer_query_webgl2.TIMESTAMP_EXT, EXT_disjoint_timer_query_webgl2.GPU_DISJOINT_EXT, OVR_multiview2.MAX_VIEWS_OVR, OCULUS_multiview.MAX_VIEWS_OVR, EXT_texture_filter_anisotropic.MAX_TEXTURE_MAX_ANISOTROPY_EXT, WEBGL_debug_renderer_info.UNMASKED_VENDOR_WEBGL, WEBGL_debug_renderer_info.UNMASKED_RENDERER_WEBGL] but is " + value;
    }

    public static boolean isValid(final int value) {
      return WebGL2RenderingContext.ACTIVE_TEXTURE == value || WebGL2RenderingContext.ALIASED_LINE_WIDTH_RANGE == value || WebGL2RenderingContext.ALIASED_POINT_SIZE_RANGE == value || WebGL2RenderingContext.ALPHA_BITS == value || WebGL2RenderingContext.ARRAY_BUFFER_BINDING == value || WebGL2RenderingContext.BLEND == value || WebGL2RenderingContext.BLEND_COLOR == value || WebGL2RenderingContext.BLEND_DST_ALPHA == value || WebGL2RenderingContext.BLEND_DST_RGB == value || WebGL2RenderingContext.BLEND_EQUATION == value || WebGL2RenderingContext.BLEND_EQUATION_ALPHA == value || WebGL2RenderingContext.BLEND_EQUATION_RGB == value || WebGL2RenderingContext.BLEND_SRC_ALPHA == value || WebGL2RenderingContext.BLEND_SRC_RGB == value || WebGL2RenderingContext.BLUE_BITS == value || WebGL2RenderingContext.COLOR_CLEAR_VALUE == value || WebGL2RenderingContext.COLOR_WRITEMASK == value || WebGL2RenderingContext.COMPRESSED_TEXTURE_FORMATS == value || WebGL2RenderingContext.CULL_FACE == value || WebGL2RenderingContext.CULL_FACE_MODE == value || WebGL2RenderingContext.CURRENT_PROGRAM == value || WebGL2RenderingContext.DEPTH_BITS == value || WebGL2RenderingContext.DEPTH_CLEAR_VALUE == value || WebGL2RenderingContext.DEPTH_FUNC == value || WebGL2RenderingContext.DEPTH_RANGE == value || WebGL2RenderingContext.DEPTH_TEST == value || WebGL2RenderingContext.DEPTH_WRITEMASK == value || WebGL2RenderingContext.DITHER == value || WebGL2RenderingContext.ELEMENT_ARRAY_BUFFER_BINDING == value || WebGL2RenderingContext.FRAMEBUFFER_BINDING == value || WebGL2RenderingContext.FRONT_FACE == value || WebGL2RenderingContext.GENERATE_MIPMAP_HINT == value || WebGL2RenderingContext.GREEN_BITS == value || WebGL2RenderingContext.IMPLEMENTATION_COLOR_READ_FORMAT == value || WebGL2RenderingContext.IMPLEMENTATION_COLOR_READ_TYPE == value || WebGL2RenderingContext.LINE_WIDTH == value || WebGL2RenderingContext.MAX_COMBINED_TEXTURE_IMAGE_UNITS == value || WebGL2RenderingContext.MAX_CUBE_MAP_TEXTURE_SIZE == value || WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_VECTORS == value || WebGL2RenderingContext.MAX_RENDERBUFFER_SIZE == value || WebGL2RenderingContext.MAX_TEXTURE_IMAGE_UNITS == value || WebGL2RenderingContext.MAX_TEXTURE_SIZE == value || WebGL2RenderingContext.MAX_VARYING_VECTORS == value || WebGL2RenderingContext.MAX_VERTEX_ATTRIBS == value || WebGL2RenderingContext.MAX_VERTEX_TEXTURE_IMAGE_UNITS == value || WebGL2RenderingContext.MAX_VERTEX_UNIFORM_VECTORS == value || WebGL2RenderingContext.MAX_VIEWPORT_DIMS == value || WebGL2RenderingContext.PACK_ALIGNMENT == value || WebGL2RenderingContext.POLYGON_OFFSET_FACTOR == value || WebGL2RenderingContext.POLYGON_OFFSET_FILL == value || WebGL2RenderingContext.POLYGON_OFFSET_UNITS == value || WebGL2RenderingContext.RED_BITS == value || WebGL2RenderingContext.RENDERBUFFER_BINDING == value || WebGL2RenderingContext.RENDERER == value || WebGL2RenderingContext.SAMPLE_BUFFERS == value || WebGL2RenderingContext.SAMPLE_COVERAGE_INVERT == value || WebGL2RenderingContext.SAMPLE_COVERAGE_VALUE == value || WebGL2RenderingContext.SAMPLES == value || WebGL2RenderingContext.SCISSOR_BOX == value || WebGL2RenderingContext.SCISSOR_TEST == value || WebGL2RenderingContext.SHADING_LANGUAGE_VERSION == value || WebGL2RenderingContext.STENCIL_BACK_FAIL == value || WebGL2RenderingContext.STENCIL_BACK_FUNC == value || WebGL2RenderingContext.STENCIL_BACK_PASS_DEPTH_FAIL == value || WebGL2RenderingContext.STENCIL_BACK_PASS_DEPTH_PASS == value || WebGL2RenderingContext.STENCIL_BACK_REF == value || WebGL2RenderingContext.STENCIL_BACK_VALUE_MASK == value || WebGL2RenderingContext.STENCIL_BACK_WRITEMASK == value || WebGL2RenderingContext.STENCIL_BITS == value || WebGL2RenderingContext.STENCIL_CLEAR_VALUE == value || WebGL2RenderingContext.STENCIL_FAIL == value || WebGL2RenderingContext.STENCIL_FUNC == value || WebGL2RenderingContext.STENCIL_PASS_DEPTH_FAIL == value || WebGL2RenderingContext.STENCIL_PASS_DEPTH_PASS == value || WebGL2RenderingContext.STENCIL_REF == value || WebGL2RenderingContext.STENCIL_TEST == value || WebGL2RenderingContext.STENCIL_VALUE_MASK == value || WebGL2RenderingContext.STENCIL_WRITEMASK == value || WebGL2RenderingContext.SUBPIXEL_BITS == value || WebGL2RenderingContext.TEXTURE_BINDING_2D == value || WebGL2RenderingContext.TEXTURE_BINDING_CUBE_MAP == value || WebGL2RenderingContext.UNPACK_ALIGNMENT == value || WebGL2RenderingContext.UNPACK_COLORSPACE_CONVERSION_WEBGL == value || WebGL2RenderingContext.UNPACK_FLIP_Y_WEBGL == value || WebGL2RenderingContext.UNPACK_PREMULTIPLY_ALPHA_WEBGL == value || WebGL2RenderingContext.VENDOR == value || WebGL2RenderingContext.VERSION == value || WebGL2RenderingContext.VIEWPORT == value || WebGL2RenderingContext.COPY_READ_BUFFER_BINDING == value || WebGL2RenderingContext.COPY_WRITE_BUFFER_BINDING == value || WebGL2RenderingContext.DRAW_BUFFER0 == value || WebGL2RenderingContext.DRAW_BUFFER1 == value || WebGL2RenderingContext.DRAW_BUFFER2 == value || WebGL2RenderingContext.DRAW_BUFFER3 == value || WebGL2RenderingContext.DRAW_BUFFER4 == value || WebGL2RenderingContext.DRAW_BUFFER5 == value || WebGL2RenderingContext.DRAW_BUFFER6 == value || WebGL2RenderingContext.DRAW_BUFFER7 == value || WebGL2RenderingContext.DRAW_BUFFER8 == value || WebGL2RenderingContext.DRAW_BUFFER9 == value || WebGL2RenderingContext.DRAW_BUFFER10 == value || WebGL2RenderingContext.DRAW_BUFFER11 == value || WebGL2RenderingContext.DRAW_BUFFER12 == value || WebGL2RenderingContext.DRAW_BUFFER13 == value || WebGL2RenderingContext.DRAW_BUFFER14 == value || WebGL2RenderingContext.DRAW_BUFFER15 == value || WebGL2RenderingContext.DRAW_FRAMEBUFFER_BINDING == value || WebGL2RenderingContext.FRAGMENT_SHADER_DERIVATIVE_HINT == value || WebGL2RenderingContext.MAX_3D_TEXTURE_SIZE == value || WebGL2RenderingContext.MAX_ARRAY_TEXTURE_LAYERS == value || WebGL2RenderingContext.MAX_CLIENT_WAIT_TIMEOUT_WEBGL == value || WebGL2RenderingContext.MAX_COLOR_ATTACHMENTS == value || WebGL2RenderingContext.MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS == value || WebGL2RenderingContext.MAX_COMBINED_UNIFORM_BLOCKS == value || WebGL2RenderingContext.MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS == value || WebGL2RenderingContext.MAX_DRAW_BUFFERS == value || WebGL2RenderingContext.MAX_ELEMENT_INDEX == value || WebGL2RenderingContext.MAX_ELEMENTS_INDICES == value || WebGL2RenderingContext.MAX_ELEMENTS_VERTICES == value || WebGL2RenderingContext.MAX_FRAGMENT_INPUT_COMPONENTS == value || WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_BLOCKS == value || WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_COMPONENTS == value || WebGL2RenderingContext.MAX_PROGRAM_TEXEL_OFFSET == value || WebGL2RenderingContext.MAX_SAMPLES == value || WebGL2RenderingContext.MAX_SERVER_WAIT_TIMEOUT == value || WebGL2RenderingContext.MAX_TEXTURE_LOD_BIAS == value || WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS == value || WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS == value || WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS == value || WebGL2RenderingContext.MAX_UNIFORM_BLOCK_SIZE == value || WebGL2RenderingContext.MAX_UNIFORM_BUFFER_BINDINGS == value || WebGL2RenderingContext.MAX_VARYING_COMPONENTS == value || WebGL2RenderingContext.MAX_VERTEX_OUTPUT_COMPONENTS == value || WebGL2RenderingContext.MAX_VERTEX_UNIFORM_BLOCKS == value || WebGL2RenderingContext.MAX_VERTEX_UNIFORM_COMPONENTS == value || WebGL2RenderingContext.MIN_PROGRAM_TEXEL_OFFSET == value || WebGL2RenderingContext.PACK_ROW_LENGTH == value || WebGL2RenderingContext.PACK_SKIP_PIXELS == value || WebGL2RenderingContext.PACK_SKIP_ROWS == value || WebGL2RenderingContext.PIXEL_PACK_BUFFER_BINDING == value || WebGL2RenderingContext.PIXEL_UNPACK_BUFFER_BINDING == value || WebGL2RenderingContext.RASTERIZER_DISCARD == value || WebGL2RenderingContext.READ_BUFFER == value || WebGL2RenderingContext.READ_FRAMEBUFFER_BINDING == value || WebGL2RenderingContext.SAMPLE_ALPHA_TO_COVERAGE == value || WebGL2RenderingContext.SAMPLE_COVERAGE == value || WebGL2RenderingContext.SAMPLER_BINDING == value || WebGL2RenderingContext.TEXTURE_BINDING_2D_ARRAY == value || WebGL2RenderingContext.TEXTURE_BINDING_3D == value || WebGL2RenderingContext.TRANSFORM_FEEDBACK_ACTIVE == value || WebGL2RenderingContext.TRANSFORM_FEEDBACK_BINDING == value || WebGL2RenderingContext.TRANSFORM_FEEDBACK_BUFFER_BINDING == value || WebGL2RenderingContext.TRANSFORM_FEEDBACK_PAUSED == value || WebGL2RenderingContext.UNIFORM_BUFFER_BINDING == value || WebGL2RenderingContext.UNIFORM_BUFFER_OFFSET_ALIGNMENT == value || WebGL2RenderingContext.UNPACK_IMAGE_HEIGHT == value || WebGL2RenderingContext.UNPACK_ROW_LENGTH == value || WebGL2RenderingContext.UNPACK_SKIP_IMAGES == value || WebGL2RenderingContext.UNPACK_SKIP_PIXELS == value || WebGL2RenderingContext.UNPACK_SKIP_ROWS == value || WebGL2RenderingContext.VERTEX_ARRAY_BINDING == value || EXT_disjoint_timer_query_webgl2.TIMESTAMP_EXT == value || EXT_disjoint_timer_query_webgl2.GPU_DISJOINT_EXT == value || OVR_multiview2.MAX_VIEWS_OVR == value || OCULUS_multiview.MAX_VIEWS_OVR == value || EXT_texture_filter_anisotropic.MAX_TEXTURE_MAX_ANISOTROPY_EXT == value || WEBGL_debug_renderer_info.UNMASKED_VENDOR_WEBGL == value || WEBGL_debug_renderer_info.UNMASKED_RENDERER_WEBGL == value;
    }

    @Nonnull
    public static String describe(final int value) {
      return WebGL2RenderingContext.ACTIVE_TEXTURE == value ? "ACTIVE_TEXTURE" : WebGL2RenderingContext.ALIASED_LINE_WIDTH_RANGE == value ? "ALIASED_LINE_WIDTH_RANGE" : WebGL2RenderingContext.ALIASED_POINT_SIZE_RANGE == value ? "ALIASED_POINT_SIZE_RANGE" : WebGL2RenderingContext.ALPHA_BITS == value ? "ALPHA_BITS" : WebGL2RenderingContext.ARRAY_BUFFER_BINDING == value ? "ARRAY_BUFFER_BINDING" : WebGL2RenderingContext.BLEND == value ? "BLEND" : WebGL2RenderingContext.BLEND_COLOR == value ? "BLEND_COLOR" : WebGL2RenderingContext.BLEND_DST_ALPHA == value ? "BLEND_DST_ALPHA" : WebGL2RenderingContext.BLEND_DST_RGB == value ? "BLEND_DST_RGB" : WebGL2RenderingContext.BLEND_EQUATION == value ? "BLEND_EQUATION" : WebGL2RenderingContext.BLEND_EQUATION_ALPHA == value ? "BLEND_EQUATION_ALPHA" : WebGL2RenderingContext.BLEND_EQUATION_RGB == value ? "BLEND_EQUATION_RGB" : WebGL2RenderingContext.BLEND_SRC_ALPHA == value ? "BLEND_SRC_ALPHA" : WebGL2RenderingContext.BLEND_SRC_RGB == value ? "BLEND_SRC_RGB" : WebGL2RenderingContext.BLUE_BITS == value ? "BLUE_BITS" : WebGL2RenderingContext.COLOR_CLEAR_VALUE == value ? "COLOR_CLEAR_VALUE" : WebGL2RenderingContext.COLOR_WRITEMASK == value ? "COLOR_WRITEMASK" : WebGL2RenderingContext.COMPRESSED_TEXTURE_FORMATS == value ? "COMPRESSED_TEXTURE_FORMATS" : WebGL2RenderingContext.CULL_FACE == value ? "CULL_FACE" : WebGL2RenderingContext.CULL_FACE_MODE == value ? "CULL_FACE_MODE" : WebGL2RenderingContext.CURRENT_PROGRAM == value ? "CURRENT_PROGRAM" : WebGL2RenderingContext.DEPTH_BITS == value ? "DEPTH_BITS" : WebGL2RenderingContext.DEPTH_CLEAR_VALUE == value ? "DEPTH_CLEAR_VALUE" : WebGL2RenderingContext.DEPTH_FUNC == value ? "DEPTH_FUNC" : WebGL2RenderingContext.DEPTH_RANGE == value ? "DEPTH_RANGE" : WebGL2RenderingContext.DEPTH_TEST == value ? "DEPTH_TEST" : WebGL2RenderingContext.DEPTH_WRITEMASK == value ? "DEPTH_WRITEMASK" : WebGL2RenderingContext.DITHER == value ? "DITHER" : WebGL2RenderingContext.ELEMENT_ARRAY_BUFFER_BINDING == value ? "ELEMENT_ARRAY_BUFFER_BINDING" : WebGL2RenderingContext.FRAMEBUFFER_BINDING == value ? "FRAMEBUFFER_BINDING" : WebGL2RenderingContext.FRONT_FACE == value ? "FRONT_FACE" : WebGL2RenderingContext.GENERATE_MIPMAP_HINT == value ? "GENERATE_MIPMAP_HINT" : WebGL2RenderingContext.GREEN_BITS == value ? "GREEN_BITS" : WebGL2RenderingContext.IMPLEMENTATION_COLOR_READ_FORMAT == value ? "IMPLEMENTATION_COLOR_READ_FORMAT" : WebGL2RenderingContext.IMPLEMENTATION_COLOR_READ_TYPE == value ? "IMPLEMENTATION_COLOR_READ_TYPE" : WebGL2RenderingContext.LINE_WIDTH == value ? "LINE_WIDTH" : WebGL2RenderingContext.MAX_COMBINED_TEXTURE_IMAGE_UNITS == value ? "MAX_COMBINED_TEXTURE_IMAGE_UNITS" : WebGL2RenderingContext.MAX_CUBE_MAP_TEXTURE_SIZE == value ? "MAX_CUBE_MAP_TEXTURE_SIZE" : WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_VECTORS == value ? "MAX_FRAGMENT_UNIFORM_VECTORS" : WebGL2RenderingContext.MAX_RENDERBUFFER_SIZE == value ? "MAX_RENDERBUFFER_SIZE" : WebGL2RenderingContext.MAX_TEXTURE_IMAGE_UNITS == value ? "MAX_TEXTURE_IMAGE_UNITS" : WebGL2RenderingContext.MAX_TEXTURE_SIZE == value ? "MAX_TEXTURE_SIZE" : WebGL2RenderingContext.MAX_VARYING_VECTORS == value ? "MAX_VARYING_VECTORS" : WebGL2RenderingContext.MAX_VERTEX_ATTRIBS == value ? "MAX_VERTEX_ATTRIBS" : WebGL2RenderingContext.MAX_VERTEX_TEXTURE_IMAGE_UNITS == value ? "MAX_VERTEX_TEXTURE_IMAGE_UNITS" : WebGL2RenderingContext.MAX_VERTEX_UNIFORM_VECTORS == value ? "MAX_VERTEX_UNIFORM_VECTORS" : WebGL2RenderingContext.MAX_VIEWPORT_DIMS == value ? "MAX_VIEWPORT_DIMS" : WebGL2RenderingContext.PACK_ALIGNMENT == value ? "PACK_ALIGNMENT" : WebGL2RenderingContext.POLYGON_OFFSET_FACTOR == value ? "POLYGON_OFFSET_FACTOR" : WebGL2RenderingContext.POLYGON_OFFSET_FILL == value ? "POLYGON_OFFSET_FILL" : WebGL2RenderingContext.POLYGON_OFFSET_UNITS == value ? "POLYGON_OFFSET_UNITS" : WebGL2RenderingContext.RED_BITS == value ? "RED_BITS" : WebGL2RenderingContext.RENDERBUFFER_BINDING == value ? "RENDERBUFFER_BINDING" : WebGL2RenderingContext.RENDERER == value ? "RENDERER" : WebGL2RenderingContext.SAMPLE_BUFFERS == value ? "SAMPLE_BUFFERS" : WebGL2RenderingContext.SAMPLE_COVERAGE_INVERT == value ? "SAMPLE_COVERAGE_INVERT" : WebGL2RenderingContext.SAMPLE_COVERAGE_VALUE == value ? "SAMPLE_COVERAGE_VALUE" : WebGL2RenderingContext.SAMPLES == value ? "SAMPLES" : WebGL2RenderingContext.SCISSOR_BOX == value ? "SCISSOR_BOX" : WebGL2RenderingContext.SCISSOR_TEST == value ? "SCISSOR_TEST" : WebGL2RenderingContext.SHADING_LANGUAGE_VERSION == value ? "SHADING_LANGUAGE_VERSION" : WebGL2RenderingContext.STENCIL_BACK_FAIL == value ? "STENCIL_BACK_FAIL" : WebGL2RenderingContext.STENCIL_BACK_FUNC == value ? "STENCIL_BACK_FUNC" : WebGL2RenderingContext.STENCIL_BACK_PASS_DEPTH_FAIL == value ? "STENCIL_BACK_PASS_DEPTH_FAIL" : WebGL2RenderingContext.STENCIL_BACK_PASS_DEPTH_PASS == value ? "STENCIL_BACK_PASS_DEPTH_PASS" : WebGL2RenderingContext.STENCIL_BACK_REF == value ? "STENCIL_BACK_REF" : WebGL2RenderingContext.STENCIL_BACK_VALUE_MASK == value ? "STENCIL_BACK_VALUE_MASK" : WebGL2RenderingContext.STENCIL_BACK_WRITEMASK == value ? "STENCIL_BACK_WRITEMASK" : WebGL2RenderingContext.STENCIL_BITS == value ? "STENCIL_BITS" : WebGL2RenderingContext.STENCIL_CLEAR_VALUE == value ? "STENCIL_CLEAR_VALUE" : WebGL2RenderingContext.STENCIL_FAIL == value ? "STENCIL_FAIL" : WebGL2RenderingContext.STENCIL_FUNC == value ? "STENCIL_FUNC" : WebGL2RenderingContext.STENCIL_PASS_DEPTH_FAIL == value ? "STENCIL_PASS_DEPTH_FAIL" : WebGL2RenderingContext.STENCIL_PASS_DEPTH_PASS == value ? "STENCIL_PASS_DEPTH_PASS" : WebGL2RenderingContext.STENCIL_REF == value ? "STENCIL_REF" : WebGL2RenderingContext.STENCIL_TEST == value ? "STENCIL_TEST" : WebGL2RenderingContext.STENCIL_VALUE_MASK == value ? "STENCIL_VALUE_MASK" : WebGL2RenderingContext.STENCIL_WRITEMASK == value ? "STENCIL_WRITEMASK" : WebGL2RenderingContext.SUBPIXEL_BITS == value ? "SUBPIXEL_BITS" : WebGL2RenderingContext.TEXTURE_BINDING_2D == value ? "TEXTURE_BINDING_2D" : WebGL2RenderingContext.TEXTURE_BINDING_CUBE_MAP == value ? "TEXTURE_BINDING_CUBE_MAP" : WebGL2RenderingContext.UNPACK_ALIGNMENT == value ? "UNPACK_ALIGNMENT" : WebGL2RenderingContext.UNPACK_COLORSPACE_CONVERSION_WEBGL == value ? "UNPACK_COLORSPACE_CONVERSION_WEBGL" : WebGL2RenderingContext.UNPACK_FLIP_Y_WEBGL == value ? "UNPACK_FLIP_Y_WEBGL" : WebGL2RenderingContext.UNPACK_PREMULTIPLY_ALPHA_WEBGL == value ? "UNPACK_PREMULTIPLY_ALPHA_WEBGL" : WebGL2RenderingContext.VENDOR == value ? "VENDOR" : WebGL2RenderingContext.VERSION == value ? "VERSION" : WebGL2RenderingContext.VIEWPORT == value ? "VIEWPORT" : WebGL2RenderingContext.COPY_READ_BUFFER_BINDING == value ? "COPY_READ_BUFFER_BINDING" : WebGL2RenderingContext.COPY_WRITE_BUFFER_BINDING == value ? "COPY_WRITE_BUFFER_BINDING" : WebGL2RenderingContext.DRAW_BUFFER0 == value ? "DRAW_BUFFER0" : WebGL2RenderingContext.DRAW_BUFFER1 == value ? "DRAW_BUFFER1" : WebGL2RenderingContext.DRAW_BUFFER2 == value ? "DRAW_BUFFER2" : WebGL2RenderingContext.DRAW_BUFFER3 == value ? "DRAW_BUFFER3" : WebGL2RenderingContext.DRAW_BUFFER4 == value ? "DRAW_BUFFER4" : WebGL2RenderingContext.DRAW_BUFFER5 == value ? "DRAW_BUFFER5" : WebGL2RenderingContext.DRAW_BUFFER6 == value ? "DRAW_BUFFER6" : WebGL2RenderingContext.DRAW_BUFFER7 == value ? "DRAW_BUFFER7" : WebGL2RenderingContext.DRAW_BUFFER8 == value ? "DRAW_BUFFER8" : WebGL2RenderingContext.DRAW_BUFFER9 == value ? "DRAW_BUFFER9" : WebGL2RenderingContext.DRAW_BUFFER10 == value ? "DRAW_BUFFER10" : WebGL2RenderingContext.DRAW_BUFFER11 == value ? "DRAW_BUFFER11" : WebGL2RenderingContext.DRAW_BUFFER12 == value ? "DRAW_BUFFER12" : WebGL2RenderingContext.DRAW_BUFFER13 == value ? "DRAW_BUFFER13" : WebGL2RenderingContext.DRAW_BUFFER14 == value ? "DRAW_BUFFER14" : WebGL2RenderingContext.DRAW_BUFFER15 == value ? "DRAW_BUFFER15" : WebGL2RenderingContext.DRAW_FRAMEBUFFER_BINDING == value ? "DRAW_FRAMEBUFFER_BINDING" : WebGL2RenderingContext.FRAGMENT_SHADER_DERIVATIVE_HINT == value ? "FRAGMENT_SHADER_DERIVATIVE_HINT" : WebGL2RenderingContext.MAX_3D_TEXTURE_SIZE == value ? "MAX_3D_TEXTURE_SIZE" : WebGL2RenderingContext.MAX_ARRAY_TEXTURE_LAYERS == value ? "MAX_ARRAY_TEXTURE_LAYERS" : WebGL2RenderingContext.MAX_CLIENT_WAIT_TIMEOUT_WEBGL == value ? "MAX_CLIENT_WAIT_TIMEOUT_WEBGL" : WebGL2RenderingContext.MAX_COLOR_ATTACHMENTS == value ? "MAX_COLOR_ATTACHMENTS" : WebGL2RenderingContext.MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS == value ? "MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS" : WebGL2RenderingContext.MAX_COMBINED_UNIFORM_BLOCKS == value ? "MAX_COMBINED_UNIFORM_BLOCKS" : WebGL2RenderingContext.MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS == value ? "MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS" : WebGL2RenderingContext.MAX_DRAW_BUFFERS == value ? "MAX_DRAW_BUFFERS" : WebGL2RenderingContext.MAX_ELEMENT_INDEX == value ? "MAX_ELEMENT_INDEX" : WebGL2RenderingContext.MAX_ELEMENTS_INDICES == value ? "MAX_ELEMENTS_INDICES" : WebGL2RenderingContext.MAX_ELEMENTS_VERTICES == value ? "MAX_ELEMENTS_VERTICES" : WebGL2RenderingContext.MAX_FRAGMENT_INPUT_COMPONENTS == value ? "MAX_FRAGMENT_INPUT_COMPONENTS" : WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_BLOCKS == value ? "MAX_FRAGMENT_UNIFORM_BLOCKS" : WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_COMPONENTS == value ? "MAX_FRAGMENT_UNIFORM_COMPONENTS" : WebGL2RenderingContext.MAX_PROGRAM_TEXEL_OFFSET == value ? "MAX_PROGRAM_TEXEL_OFFSET" : WebGL2RenderingContext.MAX_SAMPLES == value ? "MAX_SAMPLES" : WebGL2RenderingContext.MAX_SERVER_WAIT_TIMEOUT == value ? "MAX_SERVER_WAIT_TIMEOUT" : WebGL2RenderingContext.MAX_TEXTURE_LOD_BIAS == value ? "MAX_TEXTURE_LOD_BIAS" : WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS == value ? "MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS" : WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS == value ? "MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS" : WebGL2RenderingContext.MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS == value ? "MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS" : WebGL2RenderingContext.MAX_UNIFORM_BLOCK_SIZE == value ? "MAX_UNIFORM_BLOCK_SIZE" : WebGL2RenderingContext.MAX_UNIFORM_BUFFER_BINDINGS == value ? "MAX_UNIFORM_BUFFER_BINDINGS" : WebGL2RenderingContext.MAX_VARYING_COMPONENTS == value ? "MAX_VARYING_COMPONENTS" : WebGL2RenderingContext.MAX_VERTEX_OUTPUT_COMPONENTS == value ? "MAX_VERTEX_OUTPUT_COMPONENTS" : WebGL2RenderingContext.MAX_VERTEX_UNIFORM_BLOCKS == value ? "MAX_VERTEX_UNIFORM_BLOCKS" : WebGL2RenderingContext.MAX_VERTEX_UNIFORM_COMPONENTS == value ? "MAX_VERTEX_UNIFORM_COMPONENTS" : WebGL2RenderingContext.MIN_PROGRAM_TEXEL_OFFSET == value ? "MIN_PROGRAM_TEXEL_OFFSET" : WebGL2RenderingContext.PACK_ROW_LENGTH == value ? "PACK_ROW_LENGTH" : WebGL2RenderingContext.PACK_SKIP_PIXELS == value ? "PACK_SKIP_PIXELS" : WebGL2RenderingContext.PACK_SKIP_ROWS == value ? "PACK_SKIP_ROWS" : WebGL2RenderingContext.PIXEL_PACK_BUFFER_BINDING == value ? "PIXEL_PACK_BUFFER_BINDING" : WebGL2RenderingContext.PIXEL_UNPACK_BUFFER_BINDING == value ? "PIXEL_UNPACK_BUFFER_BINDING" : WebGL2RenderingContext.RASTERIZER_DISCARD == value ? "RASTERIZER_DISCARD" : WebGL2RenderingContext.READ_BUFFER == value ? "READ_BUFFER" : WebGL2RenderingContext.READ_FRAMEBUFFER_BINDING == value ? "READ_FRAMEBUFFER_BINDING" : WebGL2RenderingContext.SAMPLE_ALPHA_TO_COVERAGE == value ? "SAMPLE_ALPHA_TO_COVERAGE" : WebGL2RenderingContext.SAMPLE_COVERAGE == value ? "SAMPLE_COVERAGE" : WebGL2RenderingContext.SAMPLER_BINDING == value ? "SAMPLER_BINDING" : WebGL2RenderingContext.TEXTURE_BINDING_2D_ARRAY == value ? "TEXTURE_BINDING_2D_ARRAY" : WebGL2RenderingContext.TEXTURE_BINDING_3D == value ? "TEXTURE_BINDING_3D" : WebGL2RenderingContext.TRANSFORM_FEEDBACK_ACTIVE == value ? "TRANSFORM_FEEDBACK_ACTIVE" : WebGL2RenderingContext.TRANSFORM_FEEDBACK_BINDING == value ? "TRANSFORM_FEEDBACK_BINDING" : WebGL2RenderingContext.TRANSFORM_FEEDBACK_BUFFER_BINDING == value ? "TRANSFORM_FEEDBACK_BUFFER_BINDING" : WebGL2RenderingContext.TRANSFORM_FEEDBACK_PAUSED == value ? "TRANSFORM_FEEDBACK_PAUSED" : WebGL2RenderingContext.UNIFORM_BUFFER_BINDING == value ? "UNIFORM_BUFFER_BINDING" : WebGL2RenderingContext.UNIFORM_BUFFER_OFFSET_ALIGNMENT == value ? "UNIFORM_BUFFER_OFFSET_ALIGNMENT" : WebGL2RenderingContext.UNPACK_IMAGE_HEIGHT == value ? "UNPACK_IMAGE_HEIGHT" : WebGL2RenderingContext.UNPACK_ROW_LENGTH == value ? "UNPACK_ROW_LENGTH" : WebGL2RenderingContext.UNPACK_SKIP_IMAGES == value ? "UNPACK_SKIP_IMAGES" : WebGL2RenderingContext.UNPACK_SKIP_PIXELS == value ? "UNPACK_SKIP_PIXELS" : WebGL2RenderingContext.UNPACK_SKIP_ROWS == value ? "UNPACK_SKIP_ROWS" : WebGL2RenderingContext.VERTEX_ARRAY_BINDING == value ? "VERTEX_ARRAY_BINDING" : EXT_disjoint_timer_query_webgl2.TIMESTAMP_EXT == value ? "TIMESTAMP_EXT" : EXT_disjoint_timer_query_webgl2.GPU_DISJOINT_EXT == value ? "GPU_DISJOINT_EXT" : OVR_multiview2.MAX_VIEWS_OVR == value ? "MAX_VIEWS_OVR" : OCULUS_multiview.MAX_VIEWS_OVR == value ? "MAX_VIEWS_OVR" : EXT_texture_filter_anisotropic.MAX_TEXTURE_MAX_ANISOTROPY_EXT == value ? "MAX_TEXTURE_MAX_ANISOTROPY_EXT" : WEBGL_debug_renderer_info.UNMASKED_VENDOR_WEBGL == value ? "UNMASKED_VENDOR_WEBGL" : WEBGL_debug_renderer_info.UNMASKED_RENDERER_WEBGL == value ? "UNMASKED_RENDERER_WEBGL" : "Unknown value " + value;
    }
  }
}
